###Auth test OPTIONAL without auth
GET http://localhost:3000/optionalAuth

###Auth test OPTIONAL with auth
GET http://localhost:3000/optionalAuth
Authorization: Basic admin:admin

###Auth test OPTIONAL with invalid auth
GET http://localhost:3000/optionalAuth
Authorization: Basic admin:wrongPass

###Auth test REQUIRED
GET http://localhost:3000/requiredAuth
Authorization: Basic admin:admin

###Auth test REQUIRED invalid password
GET http://localhost:3000/requiredAuth
Authorization: Basic admin:wrongPass

###Auth test REQUIRED missing auth
GET http://localhost:3000/requiredAuth
