###Get all notes 
GET http://localhost:3000/notes/
Authorization: Basic admin:admin

###Get notes paginated
GET http://localhost:3000/notes/?page=1&pageSize=2
Authorization: Basic admin:admin

###Get notes sorted
GET http://localhost:3000/notes/?sort=id&order=desc
Authorization: Basic admin:admin


###Get note by id
GET http://localhost:3000/notes/1
Authorization: Basic admin:admin

###Create list note
POST http://localhost:3000/notes/
Authorization: Basic admin:admin
Content-Type: application/json

{
    "title": "Note title",
    "type": "list",
    "visibility": "public",
    "folderId": 2,
    "items": [
        {"body": "body 1"},
        {"body": "body 2"}
    ]
}

###Create text note
POST http://localhost:3000/notes/
Authorization: Basic admin:admin
Content-Type: application/json

{
    "name": "Note title",
    "type": "text",
    "visibility": "public",
    "folderId": 1,
    "items": [
        {"body": "text body"}
    ]
}

###Delete note
DELETE http://localhost:3000/notes/1
Authorization: Basic admin:admin

###Delete all notes
DELETE http://localhost:3000/notes/
Authorization: Basic admin:admin

###Update note
PUT http://localhost:3000/notes/1
Authorization: Basic admin:admin
Content-Type: application/json

{
    "title": "Note title",
    "type": "list",
    "visibility": "public",
    "folderId": 2,
    "items": [
        {"body": "body 1"},
        {"body": "body 2"}
    ]
}