###Get all notes no auth
GET http://localhost:3000/notes/

###Get all notes when authorized
GET http://localhost:3000/notes/
Authorization: Basic admin:admin

###Get all notes when authorized with another user
GET http://localhost:3000/notes/
Authorization: Basic user:user

###Get note by id
GET http://localhost:3000/notes/1

###Create list note
POST http://localhost:3000/notes/
Authorization: Basic admin:admin
Content-Type: application/json

{
    "title": "Note title",
    "type": "list",
    "visibility": "public",
    "folderId": 2,
    "items": [
        {"body": "body 1"},
        {"body": "body 2"}
    ]
}

###Create text note
POST http://localhost:3000/notes/
Authorization: Basic admin:admin
Content-Type: application/json

{
    "title": "Note title",
    "type": "text",
    "visibility": "public",
    "folderId": 1,
    "items": [
        {"body": "text body"}
    ]
}

###Delete note
DELETE http://localhost:3000/notes/1
Authorization: Basic admin:admin

###Delete all notes
DELETE http://localhost:3000/notes/
Authorization: Basic admin:admin

###Get note list items
GET http://localhost:3000/notes/noteitems

###Get note by id
GET http://localhost:3000/notes/1
Authorization: Basic admin:admin

###Update note
PUT http://localhost:3000/notes/1
Authorization: Basic admin:admin
Content-Type: application/json

{
    "title": "Note title",
    "type": "list",
    "visibility": "public",
    "folderId": 2,
    "items": [
        {"body": "body 1"},
        {"body": "body 2"}
    ]
}